<a href="https://colab.research.google.com/github/KudoroEsther/Files_Deep_Learning/blob/master/Pytorch_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2025/11/13

In [1]:
!pip uninstall torch torchvision torchaudio --quiet

Proceed (Y/n)? Y
Proceed (Y/n)? Y


In [2]:
!pip install torch torchvision torchaudio --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.7/899.7 MB 577.7 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 594.3/594.3 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 107.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 954.8/954.8 kB 40.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.1/193.1 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 48.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 MB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.5/267.5 MB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 MB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.3/322.3 MB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.3/39.3 MB 15.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1

In [1]:
import torch

In [2]:
torch.__version__

'2.8.0+cu126'

In [3]:
torch.cuda.is_available()

True

2025/11/14

Basic Arithmetic Operations with Tensors

In [4]:
a = torch.tensor([2.0, 4.0, 6.0])

In [5]:
a

tensor([2., 4., 6.])

In [6]:
b = torch.tensor([1.0, 2.0, 3.0])

In [7]:
b

tensor([1., 2., 3.])

In [8]:
add_result = a+b
add_result

tensor([3., 6., 9.])

In [9]:
sub_result = a -b
sub_result

tensor([1., 2., 3.])

In [10]:
mul_result = a *b
mul_result

tensor([ 2.,  8., 18.])

Task1: Create a (3,3) tensor and carry out the above computation. Verify your results manually too using the idea from matrices.

In [15]:
three  = torch.tensor([[16,9,4], [1,2,3], [4,5,6]])
three.shape

torch.Size([3, 3])

In [16]:
exp_result = three**2
exp_result

tensor([[256,  81,  16],
        [  1,   4,   9],
        [ 16,  25,  36]])

In [17]:
sqrt_result = torch.sqrt(three)
sqrt_result

tensor([[4.0000, 3.0000, 2.0000],
        [1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])

Element-wise Functions

Matrix Operations

In [18]:
A = torch.randn(3,3) #creates a 3x3 tensor that follows a normal distribution
A

tensor([[ 0.7851,  1.0641,  0.3521],
        [-1.5692, -0.7475,  0.1947],
        [-1.0361, -1.4056,  1.6121]])

In [19]:
B = torch.randn(3,4)
B

tensor([[-0.3398, -0.0251, -0.5210, -1.5594],
        [-1.1036, -0.5725,  1.0988, -0.0414],
        [-1.2649,  0.5427, -0.5833, -2.1036]])

In [21]:
matmul = torch.matmul(A,B)
matmul

tensor([[-1.8865, -0.4378,  0.5548, -2.0090],
        [ 1.1119,  0.5729, -0.1173,  2.0685],
        [-0.1357,  1.7055, -1.9451, -1.7172]])

In [22]:
v1 = torch.tensor([1.0, 2.0, 3.0])
v2 = torch.tensor([4.0, 5.0, 6.0])

In [23]:
dot_result = torch.dot(v1, v2)
dot_result

tensor(32.)

In [24]:
#torch.mm
A = torch.tensor([[1., 2.],
                  [3., 4.]])  # Shape: (2, 2)


B = torch.tensor([[5., 6.],
                  [7., 8.]])  # Shape: (2, 2)

In [25]:
C = torch.mm(A, B)
C

tensor([[19., 22.],
        [43., 50.]])

In [30]:
#torch.mm only works for 2D array
A = torch.tensor([[[1., 2.], [2., 3.]],
                  [[4., 6.],[3., 4.]]])  # 3D array


B = torch.tensor([[[5., 6.],[1., 2.]],
                  [[5., 7.],[7., 8.]]])  # 3D array

In [28]:
A.shape

torch.Size([2, 2, 2])

In [31]:
C = torch.mm(A, B)
C

RuntimeError: self must be a matrix