# Pytorch Fundamentals

In [2]:
import torch
# Check PyTorch version
print("PyTorch version:", torch.__version__)
# Check for GPU availability
if torch.cuda.is_available():
   print("Using GPU:", torch.cuda.get_device_name(0))
   device = torch.device("cuda")
else:
   print("No GPU found, using CPU.")
   device = torch.device("cpu")
# Create a tensor and move it to the available device
x = torch.tensor([1.0, 2.0, 3.0], device=device)
print("Tensor:", x)
print("Device:", x.device)

PyTorch version: 2.9.1+cpu
No GPU found, using CPU.
Tensor: tensor([1., 2., 3.])
Device: cpu


## Creating tensors

### Scalars

In [3]:
#scalar
#scalar is a single number, zero dimension tensor
scalar = torch.tensor(8)
scalar

tensor(8)

In [4]:

scalar.ndim

0

In [5]:
import numpy as np

# scalar has a dimension of 1 in numpy
sca = np.array([2,1])
sca.ndim

1

In [6]:
#.item() is used to retrieve a number from a tensor to a python integer
scalar.item()

8

### Vectors

In [7]:
# vectors are single dimension tensor but can contain many numbers
vector = torch.tensor([8,9])
vector

tensor([8, 9])

In [8]:
#checking the vector's dimension
vector.ndim

1

In [9]:
#.shape tells you how the elements inside tensors are arranged
vector.shape
# I think it show the number of elements in each square bracket in the tensor

torch.Size([2])

### Matrix

In [10]:
MATRIX = torch.tensor([[1,3],
                       [5,6]])
MATRIX

tensor([[1, 3],
        [5, 6]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

### Tensor

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [5,6,7]]]) # this is a 3d tensor
#tensors can represent anything
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape
# there is one dimension of 3 by 3. Or a single layer 3x3
# My interpretation: we have 1,3,3 because one compact element within the first outer square bracket, 3 square brackets within the second square bracket, and three comma separeted elements within the third square bracket

torch.Size([1, 3, 3])

In [16]:
# testing my theory above. I'm RIGHT!!!
TENSOR2 = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [3,5,6],
                        [5,6,7]]]) # this is a 3d tensor
#tensors can represent anything
TENSOR2.shape

torch.Size([1, 4, 3])

### Tensors from random numbers


In [17]:
# creating a random tensor of size (224, 224,3)
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
#Tensors are filled with zeros when masking  values to prevent a model from learning them
#creating a tensor with all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [19]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Tensors from a range and tensors like

In [20]:
#torch.arange(start, end, stop)
zero_ten = torch.arange(0, 10)
zero_tenn = torch.arange(0,10, 2)

zero_ten, zero_tenn

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([0, 2, 4, 6, 8]))

In [21]:
# torch.zeros_like(input) or torch.ones_like(input) returns a tensor filled with zeros or ones in the same shape as the input
ten_zeros = torch.zeros_like(input=zero_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

Tensor datatypes include: torch.float32 or torch.float, torch.float16 or torch.half, torch.float64 or torch.double, and others
<br>
Lower precision datatypes are advisable because they are faster to compute on but they are less accurate

In [22]:
# default datatype for tensors is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=device, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if true, operations performed on the tensor are recorded

float_32_tensor, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

It good practice to ensure that all tensor datatypes are the same, and they are on the same operating unit (CPU or GPU)

In [23]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [24]:
# Creating a tensor
some_tensor = torch.rand(3,4)

#Finding details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on : {some_tensor.device}") #why is the default cpu?

tensor([[0.1374, 0.3567, 0.9001, 0.0207],
        [0.7955, 0.9917, 0.4549, 0.9061],
        [0.0533, 0.5987, 0.9445, 0.8184]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on : cpu


@ and matmul perfroms matrix multiplication its output is a scalar, while * does element-wise multiplication, its output is a matrix

We transpose when the row and column of two matrices being multiplied are not equal, tranposing changes the matrix shape...

## Manipulating tensors (tensor operations)

### Basic operations

In [48]:
# adding a number to a tensor
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [49]:
#multiplying by 10
tensor *10

tensor([10, 20, 30])

In [50]:
# tensor values do not change unless reassigned, so tensor values remains 1,2,3 despite the operations
tensor
tensor=tensor-10
tensor

tensor([-9, -8, -7])

In [51]:
tensor=tensor+10

In [52]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [53]:
tensor

tensor([1, 2, 3])

In [ ]:
#element wise operation (each element multiplies its equivalent)
print(f"{tensor} * {tensor}")
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


### Matrix Multiplication

@ is the symbol for matrix multiplication<br>
@ and matmul perform matrix multiplication * performs element-wise multiplication, its output is a matrix

In [55]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [56]:
#element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [57]:
torch.matmul(tensor, tensor)

tensor(14)

In [58]:
tensor@tensor

tensor(14)

### Common errors in DL (shape errors)

In [ ]:
#Shapes need to be in the right way
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype=torch.float32)
# tensor_A.shape
tensor_B = torch.tensor([[7,10],
                         [5,6],
                         [8,9]], dtype=torch.float32)
# torch.matmul(tensor_A, tensor_B)
#gives error since the shapes are not in the right order

In [65]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[27., 17., 26.],
        [61., 39., 60.],
        [95., 61., 94.]])


In [66]:
#torch.mm is the shortcut for matmul()
torch.mm(tensor_A, tensor_B.T)

tensor([[27., 17., 26.],
        [61., 39., 60.],
        [95., 61., 94.]])

In [70]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, #in_features matches the inner dimension of the input
                          out_features=6) # out_features describes the outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}")
print(f"Output: \n{output} \nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])
Output: 
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>) 
Output shape: torch.Size([3, 6])


### Finding the min, max, mean, sum, aggregation

In [78]:
x  = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}")
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [82]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional min/max


torch.argmax() and torch.argmin() can be used to get the index of a tensor where the max and min occur respectively

In [ ]:
tensor = torch.arange(10,100, 10)
print(f"Tensor: {tensor}")

print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

### Change tensor datatype

torch.Tensor.type(dtype=None) can be used to change the datatype of tensors

In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

In [ ]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8 

### Reshaping, stacking, squeezing and unsqueezing

In [ ]:
x = torch.arange(1., 8.)
x, x.shape

In [ ]:
#add an extra dimension
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

In [ ]:
# Change view (keeps same data as original but changes view)
z = x.view(1,7)
z, z.shape


Changing the view of a tensor with torch.view() creates a new view of the same tensor. So changing the values in viewed tensor changes the original tensor values too

In [ ]:
# Changing z changes x
z[:0] = 5
z, x

In [ ]:
# Stacking tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim =0) #try changing dim to 1
x_stacked

torch.squeeze() can be used to remove all single dimensions from a tensor

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

torch.unsqueeze() can be used to add a dimension value of 1 at a specific index

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

torch.permute(input, dims) can be used to rearrange the order of axes values, where the input gets turned into a view with new dims

In [ ]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2,0,1) # shifts axix 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

## Indexing (selecting data from tensors)