# Pytorch Fundamentals

In [43]:
import torch
# Check PyTorch version
print("PyTorch version:", torch.__version__)
# Check for GPU availability
if torch.cuda.is_available():
   print("Using GPU:", torch.cuda.get_device_name(0))
   device = torch.device("cuda")
else:
   print("No GPU found, using CPU.")
   device = torch.device("cpu")
# Create a tensor and move it to the available device
x = torch.tensor([1.0, 2.0, 3.0], device=device)
print("Tensor:", x)
print("Device:", x.device)

PyTorch version: 2.9.0+cu126
Using GPU: Tesla T4
Tensor: tensor([1., 2., 3.], device='cuda:0')
Device: cuda:0


## Creating tensors

### Scalars

In [44]:
#scalar
#scalar is a single number, zero dimension tensor
scalar = torch.tensor(8)
scalar

tensor(8)

In [45]:

scalar.ndim

0

In [46]:
import numpy as np

# scalar has a dimension of 1 in numpy
sca = np.array([2,1])
sca.ndim

1

In [47]:
#.item() is used to retrieve a number from a tensor to a python integer
scalar.item()

8

### Vectors

In [48]:
# vectors are single dimension tensor but can contain many numbers
vector = torch.tensor([8,9])
vector

tensor([8, 9])

In [49]:
#checking the vector's dimension
vector.ndim

1

In [50]:
#.shape tells you how the elements inside tensors are arranged
vector.shape
# I think it show the number of elements in each square bracket in the tensor

torch.Size([2])

### Matrix

In [51]:
MATRIX = torch.tensor([[1,3],
                       [5,6]])
MATRIX

tensor([[1, 3],
        [5, 6]])

In [52]:
MATRIX.ndim

2

In [53]:
MATRIX.shape

torch.Size([2, 2])

### Tensor

In [54]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [5,6,7]]]) # this is a 3d tensor
#tensors can represent anything
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [55]:
TENSOR.ndim

3

In [56]:
TENSOR.shape
# there is one dimension of 3 by 3. Or a single layer 3x3
# My interpretation: we have 1,3,3 because one compact element within the first outer square bracket, 3 square brackets within the second square bracket, and three comma separeted elements within the third square bracket

torch.Size([1, 3, 3])

In [57]:
# testing my theory above. I'm RIGHT!!!
TENSOR2 = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [3,5,6],
                        [5,6,7]]]) # this is a 3d tensor
#tensors can represent anything
TENSOR2.shape

torch.Size([1, 4, 3])

### Tensors from random numbers


In [58]:
# creating a random tensor of size (224, 224,3)
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [59]:
#Tensors are filled with zeros when masking  values to prevent a model from learning them
#creating a tensor with all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [60]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Tensors from a range and tensors like

In [61]:
#torch.arange(start, end, stop)
zero_ten = torch.arange(0, 10)
zero_tenn = torch.arange(0,10, 2)

zero_ten, zero_tenn

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([0, 2, 4, 6, 8]))

In [62]:
# torch.zeros_like(input) or torch.ones_like(input) returns a tensor filled with zeros or ones in the same shape as the input
ten_zeros = torch.zeros_like(input=zero_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

Tensor datatypes include: torch.float32 or torch.float, torch.float16 or torch.half, torch.float64 or torch.double, and others
<br>
Lower precision datatypes are advisable because they are faster to compute on but they are less accurate

In [64]:
# default datatype for tensors is float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=device, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if true, operations performed on the tensor are recorded

float_32_tensor, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.], device='cuda:0'),
 torch.float32,
 device(type='cuda', index=0))

It good practice to ensure that all tensor datatypes are the same, and they are on the same operating unit (CPU or GPU)

In [65]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

### Getting information from tensors

In [ ]:
# Creating a tensor
some_tensor = torch.rand(3,4)

#Finding details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on : {some_tensor.device}") #why is the default cpu?

tensor([[0.9438, 0.8225, 0.2475, 0.7795],
        [0.6026, 0.4487, 0.5176, 0.6887],
        [0.3961, 0.7938, 0.8099, 0.0616]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on : cpu


## Manipulating tensors (tensor operations)